import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#F7F1EC",
        "on-background": "#2A1F1A",
        surface: "#F7F1EC",
        "surface-dim": "#E6D9D1",
        "surface-bright": "#FDF8F4",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#F3EAE4",
        "surface-container": "#EDE3DC",
        "surface-container-high": "#E6D9D1",
        "surface-container-highest": "#DDCFC6",
        "on-surface": "#2A1F1A",
        "on-surface-variant": "#6B5750",
        "inverse-surface": "#2A1F1A",
        "inverse-on-surface": "#F7F1EC",
        outline: "#B9A79D",
        "outline-variant": "#E2D4CB",
        "surface-tint": "#8C5A4A",
        primary: "#3D2A24",
        "on-primary": "#FDF8F4",
        "primary-container": "#2A1F1A",
        "on-primary-container": "#E8D5CE",
        "inverse-primary": "#E8D5CE",
        secondary: "#8C5A4A",
        "on-secondary": "#FFFFFF",
        "secondary-container": "#E8D5CE",
        "on-secondary-container": "#3D2A24",
        tertiary: "#B76E79",
        "on-tertiary": "#FFFFFF",
        "tertiary-container": "#F3E0E2",
        "on-tertiary-container": "#5C2E35",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#c6c6c6",
        "on-primary-fixed": "#1b1b1b",
        "on-primary-fixed-variant": "#474747",
        "secondary-fixed": "#efe0d4",
        "secondary-fixed-dim": "#d2c4b9",
        "on-secondary-fixed": "#211a13",
        "on-secondary-fixed-variant": "#4e453c",
        "tertiary-fixed": "#efe0d4",
        "tertiary-fixed-dim": "#d2c4b9",
        "on-tertiary-fixed": "#211a13",
        "on-tertiary-fixed-variant": "#4e453c",
        "surface-variant": "#EDE3DC",
        champagne: "#C9A27A",
        blush: "#E8D5CE",
        ivory: "#FDF8F4",
        espresso: "#3D2A24",
        rose: "#B76E79",
      },
      fontFamily: {
        serif: ["var(--font-amiri)", "var(--font-cormorant)", "serif"],
        sans: ["var(--font-ibm-plex)", "var(--font-noto-arabic)", "system-ui", "sans-serif"],
        display: ["var(--font-cormorant)", "serif"],
      },
      fontSize: {
        "2xs": ["0.6875rem", { lineHeight: "1rem" }],
      },
      spacing: {
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        "section-gap": "120px",
      },
      maxWidth: {
        container: "1440px",
      },
      borderRadius: {
        none: "0px",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(61 42 36 / 0.05)",
        card: "0 12px 40px -16px rgb(61 42 36 / 0.16)",
        soft: "0 8px 30px -12px rgb(61 42 36 / 0.12)",
        drawer: "0 25px 50px -12px rgb(42 31 26 / 0.28)",
      },
      animation: {
        "fade-in": "fadeIn 0.4s ease-out forwards",
        "slide-up": "slideUp 0.6s cubic-bezier(0.22, 1, 0.36, 1) forwards",
        "slide-in-right": "slideInRight 0.35s ease-out forwards",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideInRight: {
          "0%": { opacity: "0", transform: "translateX(-100%)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
      },
      transitionDuration: {
        "800": "800ms",
      },
      transitionTimingFunction: {
        luxury: "cubic-bezier(0.22, 1, 0.36, 1)",
      },
    },
  },
  plugins: [],
};

export default config;
