import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#fbf9f9",
        "on-background": "#1b1c1c",
        surface: "#fbf9f9",
        "surface-dim": "#dbdad9",
        "surface-bright": "#fbf9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f3",
        "surface-container": "#efeded",
        "surface-container-high": "#e9e8e7",
        "surface-container-highest": "#e3e2e2",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#4c4546",
        "inverse-surface": "#303031",
        "inverse-on-surface": "#f2f0f0",
        outline: "#7e7576",
        "outline-variant": "#cfc4c5",
        "surface-tint": "#5e5e5e",
        primary: "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1b1b1b",
        "on-primary-container": "#848484",
        "inverse-primary": "#c6c6c6",
        secondary: "#5d5f5f",
        "on-secondary": "#ffffff",
        "secondary-container": "#dfe0e0",
        "on-secondary-container": "#616363",
        tertiary: "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#211a13",
        "on-tertiary-container": "#8d8278",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#c6c6c6",
        "on-primary-fixed": "#1b1b1b",
        "on-primary-fixed-variant": "#474747",
        "secondary-fixed": "#e2e2e2",
        "secondary-fixed-dim": "#c6c6c7",
        "on-secondary-fixed": "#1a1c1c",
        "on-secondary-fixed-variant": "#454747",
        "tertiary-fixed": "#efe0d4",
        "tertiary-fixed-dim": "#d2c4b9",
        "on-tertiary-fixed": "#211a13",
        "on-tertiary-fixed-variant": "#4e453c",
        "surface-variant": "#e3e2e2",
        champagne: "#F5E6DA",
      },
      fontFamily: {
        serif: ["var(--font-playfair)", "serif"],
        sans: ["var(--font-ibm-plex-arabic)", "sans-serif"],
      },
      spacing: {
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        "section-gap": "120px",
      },
      maxWidth: {
        container: "1440px",
      },
      borderRadius: {
        none: "0px",
      },
    },
  },
  plugins: [],
};

export default config;
